### PR TITLE
I want to join the party too

### PR DESCRIPTION
**Pull request by sirikon**
Had to fix the broken link on README.md sorry :pray: :pray: :pray: :pray: :pray:

### CODE REVIEW

**Comment by Viroide** [comment]
We only accept authentic images, sorry. Please submit a photo of yourself and your credit card details.

**Comment by sirikon** [comment]
Thank you for your time. Please validate the image attached and credit card details before including it in the PR.

Definitely me and not something generated with Stable Diffusion

```
4000 0027 6000 3184
09/24
313
```

PD: I only accept validations sent with credit card details

**Comment by sirikon** [comment]
(reopening. wrong button :joy: )

**Comment by Viroide** [comment]
Sorry that credit card only works on stripe test env. Could you please provide one that works on Braintree? 

Great photo by the way

**Comment by sirikon** [comment]
Sorry as part of my religion I can only be scammed on Stripe test environment

EDIT: I can provide `4242 4242 4242 4242` if your scamming scheme microservice doesn't support SCA just yet.

**Review by Viroide — APPROVED** [review]
It adds so mutch value to the web!

MERGE THIS PLEASE!

**Pull request merged**
